# Generated by Django 4.2.7 on 2023-12-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_active', 'can blocking users')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
