# Generated by Django 4.2.7 on 2023-12-02 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('status_try', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], max_length=20, verbose_name='статус попытки')),
                ('answer_post_server', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingListSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_name', models.CharField(max_length=50, unique=True, verbose_name='название рассылки')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('mailing_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рассылки')),
                ('date_last_mailing', models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей отправки')),
                ('periodicity', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная'), ('monthly', 'Ежемесячная')], max_length=20, verbose_name='периодичность')),
                ('end_of_mailing', models.DateTimeField(default=datetime.datetime(2024, 12, 1, 20, 22, 28, 215968), verbose_name='дата и время окончания рассылки')),
                ('status_mailing', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], max_length=50, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка (настройки)',
                'verbose_name_plural': 'рассылки (настройки)',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_of_message', models.CharField(max_length=150, unique=True, verbose_name='тема письма')),
                ('message_body', models.TextField(verbose_name='тело сообщения')),
            ],
            options={
                'verbose_name': 'сообщение для рассылки',
                'verbose_name_plural': 'сообщения для рассылки',
            },
        ),
    ]
