# Generated by Django 4.2.7 on 2023-12-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglistsettings',
            name='client',
            field=models.ManyToManyField(related_name='clients', to='users.client', verbose_name='Клиент для рассылки'),
        ),
        migrations.AddField(
            model_name='mailinglistsettings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.message', verbose_name='текст рассылки'),
        ),
        migrations.AddField(
            model_name='logs',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailinglistsettings', verbose_name='рассылка'),
        ),
    ]
