# Generated by Django 4.2.7 on 2023-12-03 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailinglistsettings_end_of_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglistsettings',
            options={'permissions': [('set_status_mailing', 'can off mailing')], 'verbose_name': 'рассылка (настройки)', 'verbose_name_plural': 'рассылки (настройки)'},
        ),
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='end_of_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 58, 43, 799817), verbose_name='дата и время окончания рассылки'),
        ),
    ]
