# Generated by Django 4.2.7 on 2023-12-03 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailinglistsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglistsettings',
            options={'permissions': [('set_status_mailing', 'can set_status_mailing')], 'verbose_name': 'рассылка (настройки)', 'verbose_name_plural': 'рассылки (настройки)'},
        ),
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='end_of_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 13, 12, 38, 224567), verbose_name='дата и время окончания рассылки'),
        ),
    ]
