# Generated by Django 4.2.7 on 2023-12-03 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailinglistsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='end_of_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 15, 18, 33, 374566), verbose_name='дата и время окончания рассылки'),
        ),
    ]
